# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: group_request.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from is_msgs import image_pb2 as is__msgs_dot_image__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='group_request.proto',
  package='',
  syntax='proto3',
  serialized_pb=_b('\n\x13group_request.proto\x1a\x13is_msgs/image.proto\"G\n\x19MultipleObjectAnnotations\x12*\n\x04list\x18\x01 \x03(\x0b\x32\x1c.is.vision.ObjectAnnotationsb\x06proto3')
  ,
  dependencies=[is__msgs_dot_image__pb2.DESCRIPTOR,])




_MULTIPLEOBJECTANNOTATIONS = _descriptor.Descriptor(
  name='MultipleObjectAnnotations',
  full_name='MultipleObjectAnnotations',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='list', full_name='MultipleObjectAnnotations.list', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=44,
  serialized_end=115,
)

_MULTIPLEOBJECTANNOTATIONS.fields_by_name['list'].message_type = is__msgs_dot_image__pb2._OBJECTANNOTATIONS
DESCRIPTOR.message_types_by_name['MultipleObjectAnnotations'] = _MULTIPLEOBJECTANNOTATIONS
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

MultipleObjectAnnotations = _reflection.GeneratedProtocolMessageType('MultipleObjectAnnotations', (_message.Message,), dict(
  DESCRIPTOR = _MULTIPLEOBJECTANNOTATIONS,
  __module__ = 'group_request_pb2'
  # @@protoc_insertion_point(class_scope:MultipleObjectAnnotations)
  ))
_sym_db.RegisterMessage(MultipleObjectAnnotations)


# @@protoc_insertion_point(module_scope)
